name: Upload completed Spud iOS build

jobs:
  submit_ios:
    name: Upload existing iOS build for TestFlight
    type: submit
    params:
      build_id: 1e6975f3-e572-4eae-978c-79f8f48e4e90
      profile: production
